model:
  texture: "lbp"
  type: "cnn"
  input_shape: [416, 416, 3]
  num_classes: 3
  kernel: "linear"
  C: 1.0
  gamma: 'scale'
  n_estimators: 100
  max_depth: None

training:
  epochs: 50
  batch_size: 32

paths:
  train_dir: "datasets/train"
  valid_dir: "datasets/valid"
