model:
  texture: null
  types: ['dense_network', 'svm', 'random_forest']
  input_shape: [416, 416, 3]
  num_classes: 3

svm:
  kernel: "linear"
  C: 1.0
  gamma: 'scale'

random_forest:
  n_estimators: 100
  max_depth: null

training:
  epochs: 50
  batch_size: 32

paths:
  train_dir: "datasets/train"
  valid_dir: "datasets/valid"
